### ISSUE TITLE
Top Gun - Combat Zones (USA) cannot start a new game (save issue)

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#11]
rom another site about GBA saves

here’s only one game that contains three save codes, which is “Top Gun - Combat Zones”. It is a filthy liar, and if the game detects any of the storage types described by those save codes, it activates an anti-piracy routine and prevents you from picking any options in the main menu.

**Comment by Hydr8gon** [comment]
Heh, tricky bastard. I should probably add an option to override the GBA save type, similar to the current save type selection for NDS games. I'd put it somewhere in the settings though, because having a window pop up for every new game can be annoying. NDS games will be in a similar situation once I decide how to handle save detection there. Any method is not guaranteed to be 100% reliable, so an override option would be a good idea.

**Comment by Hydr8gon** [comment]
I think this can be closed now. I added the ability to manually set the GBA save type, including an option for none, which is what this game apparently needs. So even if it fools the auto-detection, it only takes a few clicks to override it.
