### ISSUE TITLE
windows release does not work on windows

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [Hydr8gon/NooDS#111]
you should make the windows release 32bit so it does actually WORK on windows.
or at minimum don't lie that its for windows when its not really windows compatible :P

**Comment by Hydr8gon** [comment]
Uh, 64-bit Windows is still Windows. I'm not lying about supporting it, even though that's a funny idea. If there are 32-bit versions of all the dependencies, you should be able to compile your own 32-bit builds. I distribute 64-bit builds because these run better on 64-bit computers, which is what most people have.

**Comment by CasualPokePlayer** [comment]
> don't lie that its for windows when its not really windows compatible :P

Dunno man, Windows 11 is 64 bit only, guess the latest version of Windows is not Windows compatible.

**Comment by MyTDT-Mysoft** [comment]
> > don't lie that its for windows when its not really windows compatible :P
> 
> Dunno man, Windows 11 is 64 bit only, guess the latest version of Windows is not Windows compatible.

windows 11 can still run 32bit programs

**Comment by MyTDT-Mysoft** [comment]
> Uh, 64-bit Windows is still Windows. I'm not lying about supporting it, even though that's a funny idea. If there are 32-bit versions of all the dependencies, you should be able to compile your own 32-bit builds. I distribute 64-bit builds because these run better on 64-bit computers, which is what most people have.

lol no 64bit versions dont run better on 64bit computers... thats not true... theres barely any difference...

**Comment by CasualPokePlayer** [comment]
> windows 11 can still run 32bit programs

Yes, Windows 11 keeps backwards compatiblity layers for older software. It however does not support 32 bit PCs, nor can you install a 32 bit version of Windows 11 on a 64 bit PC.

> lol no 64bit versions dont run better on 64bit computers... thats not true... theres barely any difference...

A 64 bit PC is going to be able to run 64 bit programs better than 32 bit programs for a few reasons:

1. 64 bit mode gives access to more registers than 32 bit mode.
2. 64 bit mode uses a better calling convention than 32 bit mode.
3. 64 bit versions are guarenteed to have more CPU extensions available and 32 bit versions.
4. 64 bit mode is not stuck under a compatiblity layer.
5. 64 bit mode can natively do 64 bit math, instead of requiring multiple 32 bit operations.

Also 32 bit PCs are dead, the very small minority of users that even use 32 bit PCs can just build the program themselves if it is possible. Probably not going to run well given how old the PC would have to be to have a 32 bit CPU.

**Comment by MyTDT-Mysoft** [comment]
> > windows 11 can still run 32bit programs
> 
> Yes, Windows 11 keeps backwards compatiblity layers for older software. It however does not support 32 bit PCs, nor can you install a 32 bit version of Windows 11 on a 64 bit PC.
> 
> > lol no 64bit versions dont run better on 64bit computers... thats not true... theres barely any difference...
> 
> A 64 bit PC is going to be able to run 64 bit programs better than 32 bit programs for a few reasons:
> 
> 1. 64 bit mode gives access to more registers than 32 bit mode.
> 2. 64 bit mode uses a better calling convention than 32 bit mode.
> 3. 64 bit versions are guarenteed to have more CPU extensions available and 32 bit versions.
> 4. 64 bit mode is not stuck under a compatiblity layer.
> 5. 64 bit mode can natively do 64 bit math, instead of requiring multiple 32 bit operations.
> 
> Also 32 bit PCs are dead, the very small minority of users that even use 32 bit PCs can just build the program themselves if it is possible. Probably not going to run well given how old the PC would have to be to have a 32 bit CPU.

those register access come with size and pressure costs... and they dont really help that much for most cases, because x86 being CISC have enough registers... (like you have infinite registers in forms of constants in const for example), and internally x86 have a bunch more registers for out of order execution, not to mention other things...  

callng conventions have nothing to do with "mode", you can say that "compilers" have... but fastcall isnt exactly always faster than using registers, that in the long run, would need to be preserved anyway... and have the opposite effect of REQUIRING more registers to compensate... 

all extensions so far are avaliable to 32bit and 64ibt.... and the other thing you said is talking about SSE-2... which is irrelevant already... because you it wont change anything for the newer extensions... so thats a lazy dumb excuse... 

"its not a compatibility layer"... unlike the WSL for example... and its not "stuck anywhere"

32bit can also do 64bit math trough the extensions, so yes it would help with programs that constantly require 64bit math, which is not the case here... not to mention unless you're coding in assembly, all that is subject to the compiler to decide, because 64bit people use less and less inlined assembly anyway

32 bit PCs are not dead... and even that i have a 64bit capable PC i wont waste the power and ram using a less compatible 64bit OS... (but you're right that win11 is basically not windows anymore.... but the 32bit will stand as long the windows API stands... so they are tied togheter... and all of those are lame excuses anyway to not support 32bit

**Comment by Hydr8gon** [comment]
#73 has a change that adds automatic 32-bit Windows builds. As I described both here and there, it's not something I plan to support in the main branch. However, you could fork the project and apply that change to have your own personal 32-bit autobuilds.

For what it's worth, I tested a 32-bit build on my 64-bit machine, and the native 64-bit version is about 15% faster. Unrelatedly, there seems to be an issue with the threaded 2D renderer on Windows, because both builds run like crap unless I turn that off.

**Comment by MyTDT-Mysoft** [comment]
> #73 has a change that adds automatic 32-bit Windows builds. As I described both here and there, it's not something I plan to support in the main branch. However, you could fork the project and apply that change to have your own personal 32-bit autobuilds.
> 
> For what it's worth, I tested a 32-bit build on my 64-bit machine, and the native 64-bit version is about 15% faster. Unrelatedly, there seems to be an issue with the threaded 2D renderer on Windows, because both builds run like crap unless I turn that off.

ok.... thanks... but please rename the "windows" to "windows 64-bit" at least, i will see if i can get him to do the 32bit releases :)

**Comment by fluxehub** [comment]
> > windows 11 can still run 32bit programs
> 
> Yes, Windows 11 keeps backwards compatiblity layers for older software. It however does not support 32 bit PCs, nor can you install a 32 bit version of Windows 11 on a 64 bit PC.
> 
> > lol no 64bit versions dont run better on 64bit computers... thats not true... theres barely any difference...
> 
> A 64 bit PC is going to be able to run 64 bit programs better than 32 bit programs for a few reasons:
> 
> 1. 64 bit mode gives access to more registers than 32 bit mode.
> 2. 64 bit mode uses a better calling convention than 32 bit mode.
> 3. 64 bit versions are guarenteed to have more CPU extensions available and 32 bit versions.
> 4. 64 bit mode is not stuck under a compatiblity layer.
> 5. 64 bit mode can natively do 64 bit math, instead of requiring multiple 32 bit operations.
> 
> Also 32 bit PCs are dead, the very small minority of users that even use 32 bit PCs can just build the program themselves if it is possible. Probably not going to run well given how old the PC would have to be to have a 32 bit CPU.

There's no point arguing with this guy, they did this exact same thing on the melonDS repo https://github.com/melonDS-emu/melonDS/issues/1296

**Comment by MyTDT-Mysoft** [comment]
> > > windows 11 can still run 32bit programs
> > 
> > 
> > Yes, Windows 11 keeps backwards compatiblity layers for older software. It however does not support 32 bit PCs, nor can you install a 32 bit version of Windows 11 on a 64 bit PC.
> > > lol no 64bit versions dont run better on 64bit computers... thats not true... theres barely any difference...
> > 
> > 
> > A 64 bit PC is going to be able to run 64 bit programs better than 32 bit programs for a few reasons:
> > 
> > 1. 64 bit mode gives access to more registers than 32 bit mode.
> > 2. 64 bit mode uses a better calling convention than 32 bit mode.
> > 3. 64 bit versions are guarenteed to have more CPU extensions available and 32 bit versions.
> > 4. 64 bit mode is not stuck under a compatiblity layer.
> > 5. 64 bit mode can natively do 64 bit math, instead of requiring multiple 32 bit operations.
> > 
> > Also 32 bit PCs are dead, the very small minority of users that even use 32 bit PCs can just build the program themselves if it is possible. Probably not going to run well given how old the PC would have to be to have a 32 bit CPU.
> 
> There's no point arguing with this guy, they did this exact same thing on the melonDS repo [melonDS-emu/melonDS#1296](https://github.com/melonDS-emu/melonDS/issues/1296). You can look at their other issues as well, they're effectively a troll.

no you're the retarded idiot troll

i'm being serious about support on that stuff... and i actually had been in contact with microsoft and seems there WILL BE a windows 11... 32bit released at some point its just not priority... 
so maybe i can even get to make the 32bit rever the "PAE limitation", so 32bit can run free again... 

and its very rude and retarded from you... just because i defend 32bit because few other people do... it does not make me a troll... and its not my fault that most people are blind to the truth... and just "go with the wind" when 32bit is fully capable and its still supported by microsoft... so everything on windows was suppose to have a 32bit versions

and while it makes sense i try my best to raise awareness for this... thats why most of issues on github would be related to lack of 32bit support, "just because someone isnt on the mood"

but i'm a serious programmer and i value compatibility and i hate abuses... fighting for common sense is totally not trolling...

**Comment by fluxehub** [comment]
Seek help

**Comment by MyTDT-Mysoft** [comment]
> #73 has a change that adds automatic 32-bit Windows builds. As I described both here and there, it's not something I plan to support in the main branch. However, you could fork the project and apply that change to have your own personal 32-bit autobuilds.
> 
> For what it's worth, I tested a 32-bit build on my 64-bit machine, and the native 64-bit version is about 15% faster. Unrelatedly, there seems to be an issue with the threaded 2D renderer on Windows, because both builds run like crap unless I turn that off.

oh btw... i forgot to ask... when you did the 32bit test did you compiled it using -march? because defaults for 32bit would be like "pentium".. so probabily using a new architecture (i guess for 64bit  the minimum is like P3/P4), so that by itself can cause some speed differences... to reduce such minimal 15% even further (and probabily 1-5% of that is from wow64)

**Comment by MyTDT-Mysoft** [comment]
> Please seek help, no one on earth should care this much about computer architectures

sure... can you help me spread the 32bit joy around? :D

**Comment by Absolucy** [comment]
@MyTDT-Mysoft Care to give any actual _reasons_ why 32-bit is supposedly "better"?

**Comment by SkyVelleity** [comment]
Don't mind me🍿😎

**Comment by MyTDT-Mysoft** [comment]
> @MyTDT-Mysoft Care to give any actual _reasons_ why 32-bit is supposedly "better"?

the part that is better because it works for everyone that have windows... not only those using 64bit windows... but the main point is.. it isnt WORSE than 64bit, both have the pro's and con's and while many people think i'm against 64bit i'm not... but ONLY having 64bit and ignoring 32bit... just because "majority" (that does not really choose anything) have 64bit... is what is the problem...

**Comment by pivotman319-owo** [comment]
> the part that is better because it works for everyone that have windows... not only those using 64bit windows... but the main point is.. it isnt WORSE than 64bit, both have the pro's and con's and while many people think i'm against 64bit i'm not... but ONLY having 64bit and ignoring 32bit...

Are you aware of the fact that 64-bit Windows NT features a native 32-bit compatibility layer and that AMD64 is *literally* just an extension of the existing i386/IA-32 architecture?

![Image of CFF Explorer displaying a 32-bit variant of shell32.dll from the SysWOW64 directory, on 64-bit Windows 11](https://user-images.githubusercontent.com/15126754/191758701-54b55397-8261-40bf-aeba-ead43b730648.png)

> just because "majority" (that does not really choose anything) have 64bit... is what is the problem... hence why i dont have plans to "downgrade" to 64bit... because to me, that is still using even some very nice 16bit windows programs... it would be a huge downgrade... not to mention i tend to not use newer programs because they tend to be bloated (the new generation seems to be releasing one browser with each program...) and 64bit allowing to waste memory without thinking twice... degrades most software quality...

AMD64-based productivity applications such as the latest *Blender* release and *Visual Studio 2022* are bound to outright not work on x86 Windows at all, simply because their toolsets were built for a different CPU architecture that is intentionally designed to work better in more hardware-intensive situations (the same would also apply to most video games from 2012 onwards. I'd also like to point out that there does exist a 64-bit replacement for the 16-bit NTVDM compatibility layer called *OTVDM*; alternatively, you can pop open a copy of 86box/DOSbox, get a virtual machine up and running and work your way through installing 16-bit Windows or MS-DOS from there on with a 64-bit system.

> i already had to change from 4gb of ram to 6gb of ram just to change from XP to win7... would require 8gb of ram to change from win7/32 to win7/64 just to be able to run low quality programs? no thanks :P...

*Please* upgrade your hardware - not a single person here is living on 2008/2009-era specifications to this day, and I'm saying this as a person who is running Windows 11 and pretty much almost all apps just fine on a Ryzen 5 2600 six-core processor with 16 GB of RAM installed and a GeForce GTX 1650 w/ 4 GB of VRAM.

The market share for x86-based Windows releases is astoundingly low with [only 0.2% of users worldwide running said architecture](https://store.steampowered.com/hwsurvey). AMD64 Windows is guaranteed to suffer on just 4 GB of RAM and you *will* obviously run into performance issues on such massive constraints. Microsoft has intentionally limited 32-bit Windows to run on an artificial maximum usable RAM limit of 4 GB, and it has always been this way since the early days of Windows NT, regardless of whether you have Physical Address Extension (PAE) enabled or not:

![The respective Windows product policies for memory limitations; 32-bit versions are artificially limited to just 4 GB of RAM, whereas 64-bit edition limitations are much more relaxed with up to a whopping maximum of 128 GB RAM.](https://user-images.githubusercontent.com/15126754/191763441-10c995cc-6f21-420b-9959-9fa11ee4ee8e.png)

**Comment by MyTDT-Mysoft** [comment]
yes... i'm aware of that... but thats an emulator... it does not run natively like NTVDM altough it would be usable... but then again you just said yourself "AMD64 windows is guaranteed to suffer on just 4gb of ram" and that is unacceptable to me... because the only reason it suffers is because they dont care enough to make it use less ram.... (even if optionally) even if at some sacrifice... but since they decided to abuse... i decided to counter that abuse... also MS limited the 32bit due to the number of drivers that were not 32bit PAE compatible... but that is not longer true... they should actually remove that limit (i'm actually trying to get them to do that and release an optional patch even for windows 7... to undo that unfair situation to 32bit... so that people like me wont need the unnoficial PAE patch for such...) but while i welcome having more memory... i dont welcome abusing of that just because you have it... 

and marketshare part is bullshit... because computers come with 64bit and majority of windows users think that more is always better and so on... so they didnt DECIDED into that... they just accepted because they dont know better.. altough they would always complain that windows is "slow and whatnot" but they are ALLOWING them to do that by wanting half-backed stuff that is abusing of memory... and so on... because if marketing would come clean that you can do almost as much (from the home perspective) on the 32bit... people wouldnt see a need to buy a new computer to use 64bit to run the same thing that they already had... but requiring more resources...

so i give a slack when its something huge like blender and VS that is used by the industry... altough linux is used on the industry more than windows... and dont have such problems... so thats just another excuse... but one that i tend to accept while its for a different ecosystem... and for that reason i stopped using VS in what? 2010? when their IDE became painfully slow and bloated for no good reason... (and the irony that their VSCode runs much better on lnux than it does on windows)

and no... i wont upgrade my hardware just to cope with abuses... not until you start saying the same thing to other people "oh you got raped? just suck it up and upgrade yourself!" because i feel the same way with all this hardware/software abuse... and no "unfair" statistics or whatever will change that.

but on the other hand... if they make a win10 64bit version that can run on 256mb of ram (assuming that i would only use the same software used back on those days)... and that it would be actually faster at the same thing than it was... then i would call that an improvement... otherwise... dont bother... i would only upgrade when its indeed an upgrade... shoving useless security of heavy UI's and bunch of lazy useless stuff in my face and calling that upgrade... is not something i will ever accept...

**Comment by dangeredwolf** [comment]
But is it truly Windows compatible if I can't run it on Windows 3.1? 🤔

**Comment by fluxehub** [comment]
You are delusional to a point where I'm genuinely concerned for your mental health

**Comment by Hydr8gon** [comment]
This is getting out of hand.
