### ISSUE TITLE
James Pond - Codename Robocod black screen

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#18]
After selecting the language the screen goes black and just music playing.

**Comment by fleroviux** [comment]
There's a delay roughly between 4-7 cycles from when a component asserts the ARM7's IRQ line to when the IRQ is handled. 
You'll want to somewhat take care of this to get past the black screen. Although care must be taken, since using the wrong delay or incorrect logic can easily break things elsewhere.

**Comment by Hydr8gon** [comment]
Thanks! This seems like something that I can try to handle once I figure out how I want to handle timing.
