### ISSUE TITLE
Spellbound (Europe) corrupt line on menu

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#31]
![spellbound](https://user-images.githubusercontent.com/2696404/84479126-ff005200-acc4-11ea-964c-f3dfa82c5b37.PNG)

**Comment by Arisotura** [comment]
context on this bastard:

stupid game uses a shitty way of sending GX display lists.

basically, it will send the first chunk of data, then set an IRQ handler to send the next chunk when the GXFIFO is less than half-full.

except that, as soon as the function initializing that has returned, it sends a SWAP_BUFFERS command, without checking whether the transfer was actually finished.

so basically GX execution must be fast enough that the GXFIFO is already less than half-full when the current DMA finishes, so the next one starts immediately. otherwise, you'd return too early and have a SWAP_BUFFERS inserted in the middle of the display list, which, you guess how that goes.

**Comment by Hydr8gon** [comment]
Looks like this is fixed by b49fb0a. I'll have to keep an eye on it though, if I start working on GXFIFO timing.
