### ISSUE TITLE
Version for Ps Vita

### ISSUE THREAD

**Issue by julioapc16** [Hydr8gon/NooDS#45]
Hello Friend you can release a version for Ps Vita, The Vita community thanks you.

**Comment by Hydr8gon** [comment]
I don't really consider the Vita version ready for release right now, which is why it's not even merged into the main branch yet. At the very least, I'd want to make an actual UI for it before doing so. There's also the issue that it's still really slow! For now, here's a list of commands that will rebase the Vita build on the latest source and compile it. Or you can hop in the Discord and ask me for a build; I don't mind posting them there.
```
git clone https://github.com/Hydr8gon/NooDS.git -b vita
cd NooDS
git rebase origin/master
mkdir build-vita
cd build-vita
cmake ..
make
```

**Comment by julioapc16** [comment]
Friend, I'm glad that you will be working on a version for Vita, and  community dream of a DS emulator running on Vita, don't be in a hurry, when that version is ready it will surely be incredible.

**Comment by Hydr8gon** [comment]
Well, I ended up committing the Vita port to the main branch! It's still very slow, but it's at least more user-friendly with a basic file browser and proper screen layouts. Guess that means this can be closed :)
