### ISSUE TITLE
Android minimal version.

### ISSUE THREAD

**Issue by Loughty** [Hydr8gon/NooDS#63]
Sorry, a basic information that a think it's missing in the readme. What are the minimal version of Android compatible? And also, other requisites could be nice too, like the minimal ram and the GHz/cores of processor needed for a nice experience.

I tend to convert the obsolete hardware (like old android 2.3 or 4.0 phones) to improvised game consoles, gives it a second life; so, this type of information are very useful to see what I could use and what not. Very thanks to all ^^.

**Comment by Hydr8gon** [comment]
According to the build.gradle file, the minimum SDK version is 16, so that would be Android 4.1. I can't remember why I chose 4.1 over 4.0 or lower, but I think there was some reason.

As for minimum specs, that's pretty hard to define. I have a OnePlus 5T with a Snapdragon 835; with something like that, you can expect to get full speed in most 2D games and some light 3D games. Of course, I'm continuously working on optimizations and such, so the "minimum" specs are never set in stone.

RAM shouldn't be a concern, at least. At baseline it should only use a few dozen MBs at most, and past that it will only try to load ROMs into memory if there's enough room (otherwise it falls back to reading from file).

**Comment by ResurrectionRedmi9** [comment]
Android 7.0 nougat with vulkan support is the minimum hw requirements for future (IMOO).

**Comment by Loughty** [comment]
Thanks to all, so, for the moments, the software requisites are Android 4.1, and the hardware (CPU at least) vary depending of the game (if have a problem, I just have to stuck on the 2D games). Thanks again, see us later!
