### ISSUE TITLE
Vita Version super slow

### ISSUE THREAD

**Issue by MuddserAhmed** [Hydr8gon/NooDS#64]
Is it true that only one Vita core is being used resulting in 7 FPS in 99% titles?

**Comment by Hydr8gon** [comment]
Rendering is threaded, and it can use up to 3 cores available (the fourth one is reserved for the OS). The bigger issue is that the Vita CPU is very slow, and it might not ever be possible to have full speed DS emulation on it.

**Comment by MuddserAhmed** [comment]
Sorry to bother you if i felt dumb to you there are more vita players wondering the same you said it can use 3 cores but i used vitashell plugin and there only one core is stressed out others are at like 2-5 % usage as they are on livearea or in home so is there a problem?
https://imgur.com/a/2sM2WDM

**Comment by Hydr8gon** [comment]
It depends on what's running. Since it's just a logo screen in that screenshot, there's no 3D work to do and very little 2D work to do, so it makes sense that the rendering threads aren't very active. Here's what it looks like in-game in SM64DS:
![2021-09-25-192557](https://user-images.githubusercontent.com/3057954/134788353-256befdf-0bd9-4f6b-bf72-0f5024d9ce2b.jpg)

**Comment by MuddserAhmed** [comment]
Sike Makes sense guess Vita's hardware is not worth it.

**Comment by Hydr8gon** [comment]
Closing this because it's not really a bug. I'll continue working on improving performance though.
