### ISSUE TITLE
Golden Sun - Depth issues

### ISSUE THREAD

**Issue by benderscruffy** [Hydr8gon/NooDS#7]
The carpet is rendered over character sprites
![golden](https://user-images.githubusercontent.com/2696404/84136854-71cbbc00-aa7e-11ea-8737-271e29551451.PNG)
[Golden.Sun.USA.Europe.zip](https://github.com/Hydr8gon/NooDS/files/4751559/Golden.Sun.USA.Europe.zip)
here is a save if need be

**Comment by Hydr8gon** [comment]
Strange. The BG layer that contains the carpet is given priority 2, and the character sprites are all given a lower priority of 3. This will need more looking into.

Thanks for the save by the way, it's super helpful :)

**Comment by fleroviux** [comment]
NanoboyAdvance has also had this issue. It's an undocumented / improperly documented edge-case in the OBJ renderer.
Quoting myself:
> Golden Sun makes clever usage of OBJ rendering behavior, that isn't properly documented in GBATEK.
It uses transparent OBJs to hijack the priority of the character OBJs.
\
This works because:
\
OBJs are rendered in forward order
higher priority OBJ pixels always update the OBJ buffer priority, even if the pixel transparent.
lower priority OBJ pixels always write the OBJ buffer if it's currently transparent.

I fixed this in https://github.com/fleroviux/NanoboyAdvance/commit/e4483830a9c4c630352866d5306f91787d8e7ed2

**Comment by Hydr8gon** [comment]
Heh, tricky. I'll have to rework object rendering a bit for this, but I'll see what I can do. Thanks!

**Comment by Hydr8gon** [comment]
Interesting note on this: the behavior was "fixed" on the DS. When I first implemented this I did it for both DS and GBA mode, but it broke the title screen in Mario & Luigi: Partners in Time. I had a suspicion, so I tested it by loading up Golden Sun in GBARunner2, since it runs GBA games in DS mode. Sure enough, the priority issue was there.
